### ISSUE TITLE
Corrections sur le process de connexion

### ISSUE THREAD

**Issue by maitre-hibou** [MytiX/BileMo#5]
[src/Controller/ApiLoginController.php](https://github.com/MytiX/BileMo/blob/master/src/Controller/ApiLoginController.php)

Ce controller n'est pas vraiment nécessaire. Seule la définition de la route l'est. 

Dans le security.yaml, tu définis :
```yaml
security:
    firewalls:
        main:
            json_login:
                check_path: app_api_login
                success_handler: 'App\Security\AuthentificationHandler\AuthenticationSuccessHandler'
                failure_handler: 'App\Security\AuthentificationHandler\AuthenticationFailureHandler'
            stateless: true
```
 Le `check_path` est une route qui est interceptée par le systeme de sécurité de Symfony pour vérifier les crédentials envoyés par l'utilisateur. Il n'y a pas besoin de définir de controller, car quand on arrive sur cette route, on passe dans le process d'authentification.

[src/Repository/UserRepository.php](https://github.com/MytiX/BileMo/blob/master/src/Repository/UserRepository.php)

N'oublie pas de supprimer le code commenté qui n'est pas utilisé ici.
